version: '3.8'

services:
  app:
    container_name: tghbot
    build:
      context: .
      dockerfile: Dockerfile
    command: bash start.sh
    restart: on-failure
    ports:
      - "80:80"
      - "8090:8090"
      - "4000:4000"
      - "6090:6090"

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - WEBUI_PORT=8090
    volumes:
      - /path/to/config:/config
      - /path/to/downloads:/downloads
    ports:
      - "8090:8090"

volumes:
  db_data:
